--SET IDENTITY_INSERT Specialisations ON
INSERT INTO Specialisations(Id, SpecialisationName) VALUES
(1, 'Allergy and Immunology'),
(2, 'Anesthesiology'),
(3, 'Cardiology'),
(4, 'Colon and Rectal Surgery'),
(5, 'Dermatology'),
(6, 'Emergency Medicine'),
(7, 'Endocrinology'),
(8, 'Family Medicine'),
(9, 'Forensic Pathology'),
(10, 'Gastroenterology'),
(11, 'General Surgery'),
(12, 'Geriatrics'),
(13, 'Hematology'),
(14, 'Infectious Disease'),
(15, 'Internal Medicine'),
(16, 'Neonatology'),
(17, 'Nephrology'),
(18, 'Neurology'),
(19, 'Neurological Surgery'),
(20, 'Obstetrics and Gynecology'),
(21, 'Oncology'),
(22, 'Ophthalmology'),
(23, 'Orthopedic Surgery'),
(24, 'Otolaryngology (ENT)'),
(25, 'Pathology'),
(26, 'Pediatrics'),
(27, 'Physical Medicine and Rehabilitation'),
(28, 'Plastic Surgery'),
(29, 'Preventive Medicine'),
(30, 'Psychiatry'),
(31, 'Pulmonology'),
(32, 'Radiology'),
(33, 'Rheumatology'),
(34, 'Sleep Medicine'),
(35, 'Sports Medicine'),
(36, 'Thoracic Surgery'),
(37, 'Urology'),
(38, 'Vascular Surgery');
